#pragma once

#include "ca4G.h"
using namespace CA4G;

#include "Techniques/GUI_Traits.h"

#include "Techniques/Common/ConstantBuffers.h"
#include "Techniques/Common/RetainedSceneLoader.h"
#include "Techniques/Sample/Sample.h"
#include "Techniques/RetainedBasic/RetainedBasicRenderer.h"
#include "Techniques/Tutorials/Tutorial1.h"
#include "Techniques/Tutorials/Tutorial2.h"
#include "Techniques/Tutorials/Tutorial3.h"
#include "Techniques/Tutorials/Tutorial4.h"
#include "Techniques/Tutorials/Tutorial5.h"
#include "Techniques/Tutorials/Tutorial6.h"
#include "Techniques/Tutorials/Tutorial7.h"
#include "Techniques/Tutorials/Tutorial8.h"
#include "Techniques/Tutorials/Tutorial9.h"
#include "Techniques/Tutorials/Tutorial10.h"
#include "Techniques/Tutorials/Tutorial11.h"
#include "Techniques/Tutorials/Tutorial12.h"
#include "Techniques/DeferredShading/DeferredLighting.h"
#include "Techniques/DXR_Raytracer/DXRRaytracer.h"
#include "Techniques/DXR_Photontracer/DXRPhotonMapping.h"
#include "Techniques/RASTER_DXR_Photontracer/HybridPhotonTracer.h"
#include "Techniques/AccPathtracing/DXRPathtracer.h"
#include "Techniques/ItAccPathtracing/DXRItPathtracer.h"
#include "Techniques/FULL_DXR_PhotonMap2/FullDXRPhotontracerTechnique2.h"
#include "main.h"
